import { it, expect } from 'vitest'
import { Stack } from './index'

it('should push, pop, and peek', () => {
  const stack = new Stack()
  stack.push(1)
  stack.push(2)
  stack.push(3)
  expect(stack.pop()).toBe(3)
  expect(stack.pop()).toBe(2)
  expect(stack.pop()).toBe(1)
  expect(stack.pop()).toBe(undefined)
  stack.push(1)
  stack.push(2)
  stack.push(3)
  expect(stack.peek()).toBe(3)
  expect(stack.peek()).toBe(3)
  expect(stack.pop()).toBe(3)
  expect(stack.peek()).toBe(2)
  expect(stack.pop()).toBe(2)
  expect(stack.peek()).toBe(1)
  expect(stack.pop()).toBe(1)
  expect(stack.peek()).toBe(undefined)
  expect(stack.pop()).toBe(undefined)
})
